import { EventObjectString } from '../type/event-utils';

export const ERROR_CORE_APP: EventObjectString = {
  'BFF-AU-01': 'User login ไม่ถูกต้อง',
  'BFF-AU-02': 'access token ไม่ถูกต้อง',
  'BFF-AU-03': 'ไม่มีสิทธิ์เข้าถึง',
  'BFF-AU-05': 'ไม่มีสิทธิ์เข้าถึง',
  'BFF-TN-01': 'ไม่พบ Superapp order token ref',
  'BFF-SE-01': 'สถานะ order service ไม่ถูกต้อง',
  'BFF-SE-02': 'Order service error',
  'BFF-IN-01': 'Superapp internal error',
  'BFF-SE-03': 'ไม่พบ Order service transaction',
  'BFF-SE-04': 'Customer service error.',
  'BFF-RE-01': 'Redis internal error.',
  'BFF-RE-02': 'ไม่พบ Key',
  'BFF-RE-03': 'ไม่พบ UserId',
  'BFF-RE-05': 'Someone is reviewing this transaction.',
  'BFF-RE-06': 'ไม่พบ TransactionId',
  'BFF-SE-05': 'ไม่พบ Superapp account',
  'BFF-SE-06': 'สถานะลูกค้าเป็น Inactive',
  'BFF-SE-07': 'Status is not pending',
  'BFF-SE-08': 'Customer error',
  'BFF-SE-09': 'สถานะไม่เป็น approve หรือ reject',
  'BFF-SE-10': 'Earn service error.',
  'BFF-SE-11': 'Redis service error.',
  'BFF-SE-12': 'เนื่องจากเลขที่ใบเสร็จซ้ำ',
  'BFF-SE-13': 'Invalid receiptId.',
  'BFF-SE-14': 'ชื่อร้านค้าไม่ถูกต้อง',
  'BFF-SE-15': 'Invalid merchant identifier.',
  'BFF-SE-16': 'ยอดรวมต้องมากกว่า 0 ',
  'BFF-SE-17': 'receipt date ไม่ถูกต้อง',
  'BFF-SE-18': 'Invalid building.',
  'BFF-SE-19': 'Invalid review by.',
  'BFF-SE-20': 'Invalid reject reason.',
  'BFF-SE-21': 'Revert service error.',
  'BFF-SE-22': 'Order service, Something went wrong.',
  'BFF-SE-23': 'This transaction has been rejected automatically',
  'BFF-SE-24': 'Auto Reject error',
  'BFF-LY-01': 'Loyalty earn internal error',
  'BFF-LY-02': 'เลขที่ใบเสร็จซ้ำ',
  'BFF-LY-03': 'เลขบัตรประชาชนหรือเลขที่หนังสือเดินทางมีในระบบแล้ว',
  'BFF-TE-00': 'Internal server error.',
  'BFF-TE-01': 'Path not found.',
  'BFF-TE-02': 'Validate payload error.',
  'BFF-TE-03': 'External API error.',
  'BFF-TE-04': 'Authentication error.',
  'BFF-TE-05': 'Transaction field in header was wrong.',
  'BFF-TE-06': 'Server time out.',
  'RCT-RC-01': 'เลขที่ใบเสร็จซ้ำ กรุณาเปลี่ยนใหม่',
  'RCT-RC-02': 'ไม่สามารถสะสมใบเสร็จย้อนหลังได้เกิน 1 เดือน',
  'RCT-RC-03': 'เลขที่ใบเสร็จนี้อาจจะซ้ำ กรุณากดยืนยันเพื่อสะสม',
  'RCT-TE-02': 'Validate payload error.',
  'CUS-CS-01': 'กรุณาใส่ข้อมูลที่จำเป็นให้ครบ',
  'CUS-CS-02': 'ไม่พบ Account ของ SuperApp',
  'CUS-CS-03': 'เลขบัตรประชาชนหรือเลขที่หนังสือเดินทางมีในระบบแล้ว',
  'CUS-CS-04': 'ไม่พบ Account User',
  'CUS-CS-05': 'Account User นี้ไม่ได้เป็น Shopper',
  'CUS-CS-06': 'Account User นี้ไม่ได้เป็น Viz',
  'CUS-CS-07': 'มี Account นี้อยู่ในระบบแล้ว',
  'CUS-CS-08': 'Either citizenId or passportNo must be present',
  'CUS-CS-09': 'สร้าง VIZ account เกิดข้อผิดพลาด',
  'CUS-CS-10': 'อัพเดทข้อมูลไม่สำเร็จ',
  'CUS-CS-11': 'สร้าง Customer ไม่สำเร็จ',
  'CUS-CS-12': 'สร้าง Shopper account ไม่สำเร็จ',
  'CUS-CS-13': 'อัพเดทข้อมูล VIZ ไม่สำเร็จ',
  'CUS-CM-01': 'กรุณาใส่ข้อมูลที่จำเป็นให้ครบ',
  'CUS-CM-02': 'Validate payload error.',
  'CMP-RC-01': 'ไม่มี Campaign ในระบบ',
  'CMP-RC-02': 'โค้วต้าลูกค้าหมดแล้ว',
  'CMP-RC-03': 'Campaign หมดอายุการใช้งาน',
  'CMP-RC-04': 'Campaign มีอยู่แล้วในระบบ',
  'CMP-RC-05': 'โค้วต้าทั้งหมดของลูกค้าหมดแล้ว',
  'CMP-RC-06': 'โค้วต้าวันนี้ของลูกค้าหมดแล้ว',
  'CMP-RC-07': 'โค้วต้าทั้งหมดของรางวัลหมดแล้ว',
  'CMP-RC-08': 'โค้วต้าของรางวัลเดือนนี้หมดแล้ว',
  'CMP-RC-09': 'โค้วต้าของรางวัลสัปดาห์นี้หมดแล้ว',
  'CMP-RC-10': 'โค้วต้าของรางวัลวันนี้หมดแล้ว',
  'CMP-RC-11': 'ใบเสร็จนี้ ไม่สามารถแลกของรางวัลได้ เนื่องจาก ถูกใช้ไปกับแคมเปญอื่นแล้ว กรุณาเลือกใบเสร็จใหม่',
  'CMP-RC-12': 'แคมเปญนี้ ไม่สามารถแลกของรางวัลได้ เนื่องจาก โค้วต้าหมดแล้ว กรุณาลองใหม่อีกครั้ง',
  'CMP-TE-02': 'Validate payload error.',
  'LOY-TU-01': 'identifier ไม่ถูกต้อง',
  'LOY-TU-02': 'ไม่พบ Account นี้',
  'LOY-TU-03': 'ไม่สามารถ Update ข้อมูล tier ได้',
  'LOY-TU-04': 'ไม่สามารถ Upgrade ข้อมูล tier ได้',
  'LOY-TU-05': 'ไม่สามารถ Downgrade ข้อมูล Tier ได้',
  'LOY-TE-01': 'Internal server error',
  'LOY-BL-01': 'Cannot get customer profile from Perx system',
  'LOY-IV-01': 'เนื่องจากข้อมูลร้านค้าไม่สมบูรณ์ กรุณาติดต่อเจ้าหน้าที่',
};
